server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-event?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    #password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  app:
    secret-key : etst
    exp=iration-time : 10000